version: "3.3"

services:
  nodeseek-signin:
    build: .
    image: yowiv/nodeseek-signin:latest
    container_name: nodeseek-signin
    environment:
      - IN_DOCKER=true
    env_file:
      - .env
    volumes:
      - ./cookie:/app/cookie
    command: ["python", "scheduler.py"]
    restart: always
